language: php
php:
 - 5.6
env:
  global:
   - GIT_NAME: "'Couscous auto deploy'"
   - GIT_EMAIL: d.negrier@thecodingmachine.com
   - GH_REF: github.com/thecodingmachine/best-practices
   - secure: DqH45XSmGKzMHBgTze+4oErUiwkWeWsclmci+A3yJYXgqJRFKi4UZhE/BhH2JJBF4XwKp4eMl1FREru2r7RoZLvyIl4Ky6XR2qPikMR+Em5KXUYvAXNBeeyO80gmJ1w2k2GdDpDvbsHN9atd75KBvJyAf6g8532JY7tIfFyMjdLmMzwWBHkQD6iTv5srQDUxRVEAZbqKjmfj8zLcsWG/NiMuOL8Y6V4gnbkL8Vd7QCjIk2XZkdIuxtVp6tmF+mzWVODWiytkvTTMoslGDFSCeBAlfSvso1hAZg1T/G6d08rBMD7ZdILrI5iZadJ/HejYOlYcXb5FrDzZGpMV7cjrcwU3X5bJO0acNWZYdFWiBtfKzsrAHvOtaIp7uugr9c0fJi++UUoHh9Ceia3q0xiZQf4oGP3lMVssdvHExJIEYV/u5zAE+/VB9Fv5s4TWRLc5MzwFpt37hf593Vz9ffkXIYB6kjojKFqMOudYQthCc54Gkf/URXa1ecGBxBVYUyFbk2xqgaxrsdE2Ea6UFxqhKZjujHmyNslgwv96/A+AVXRoTDuuEb0/jKS/IRioQY2lJj0CRfj+9i6xsvGmj2flqWgNk85LjUZIvvVUfk915nMMb6fBaOoGTTyRt13Th2h4u4+nhzBNqnj7IpCfvQV1gTRCmiY8/Yfx5BV8AKcPofc=
before_script:
 - composer install --no-progress
 - npm install
 - bower install
 - gulp
script:
 - vendor/bin/couscous travis-auto-deploy --php-version=5.6
